[project]
name = "signal-processor"
version = "0.3.0"
description = "Десктопное приложение для анализа спектров"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["pyqt6>=6.11.0", "pandas>=3.0.5", "numpy>=2.5.3"]

[dependency-groups]
build = ["pyinstaller>=6.22.2"]
dev = ["basedpyright>=1.40.0", "pandas-stubs>=3.0.5.260730", "ruff>=0.16.6"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv]
package = false
